### ISSUE TITLE
Plots not showing up

### ISSUE THREAD

**Issue by ekatko1** [QCBSRworkshops/workshop09#17]
When I go to: 
[https://r.qcbs.ca/workshop09/book-en/principal-component-analysis.html](https://r.qcbs.ca/workshop09/book-en/principal-component-analysis.html)

The plots are not showing up.

**Comment by pedrohbraga** [comment]
Hi, @ekatko1! Thank you for letting us know about this problem. We will add this to the list of issues to be repaired.

For the development, this issue appears because the current document fetches figures from files instead of generating them using code. The correction here is to produce the plots exclusively using code (making it more reproducible). The presentation material has all code required to perform these corrections.
